# Generated by Django 3.0.8 on 2020-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(default='Kyle Brown', max_length=200),
            preserve_default=False,
        ),
    ]
